
-- Tabela para o Diário de Dor do Paciente
CREATE TABLE IF NOT EXISTS public.diario_dor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id UUID REFERENCES public.perfis(id) ON DELETE CASCADE NOT NULL,
    intensidade INTEGER NOT NULL CHECK (intensidade >= 1 AND intensidade <= 10),
    data_registro TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela para o Checklist de Exercícios do Paciente
CREATE TABLE IF NOT EXISTS public.checklist_exercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id UUID REFERENCES public.perfis(id) ON DELETE CASCADE NOT NULL,
    exercicio_id TEXT NOT NULL,
    concluido BOOLEAN DEFAULT false,
    data_conclusao TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.diario_dor ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checklist_exercicios ENABLE ROW LEVEL SECURITY;

-- Políticas para diario_dor
CREATE POLICY "Pacientes gerenciam seu próprio diário de dor" ON public.diario_dor
    FOR ALL USING (auth.uid() = paciente_id);

CREATE POLICY "Fisios veem diário de dor dos pacientes vinculados" ON public.diario_dor
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.pacientes p
            JOIN public.perfis prof ON p.email = prof.email
            WHERE prof.id = diario_dor.paciente_id
            AND p.fisioterapeuta_id = auth.uid()
        )
    );

-- Políticas para checklist_exercicios
CREATE POLICY "Pacientes gerenciam seu próprio checklist" ON public.checklist_exercicios
    FOR ALL USING (auth.uid() = paciente_id);

CREATE POLICY "Fisios veem checklist dos pacientes vinculados" ON public.checklist_exercicios
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.pacientes p
            JOIN public.perfis prof ON p.email = prof.email
            WHERE prof.id = checklist_exercicios.paciente_id
            AND p.fisioterapeuta_id = auth.uid()
        )
    );
